classDiagram

class Owner{
    +String owner_name
    +String pet_name
    +String species
    +get_pet_info()
}

class Task{
    +String title
    +int duration
    +String priority
    +to_dict()
}

class Scheduler{
    +Owner owner
    +List tasks
    +add_task()
    +sort_tasks()
    +filter_tasks()
    +detect_conflicts()
    +generate_schedule()
    +display_schedule()
}

Owner --> Scheduler
Scheduler --> Task

